<!doctype html>
<head>
	<base href="<?PHP echo $this->base; ?>" />
	<meta charset="utf-8">
	<title>RSS Reader</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
	<link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />

	<!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
	<link rel="shortcut icon" href="favicon.ico">
	<link rel="apple-touch-icon" href="apple-touch-icon.png">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/style.css">
</head>
<body class="<?php
		echo $this->publicMode===true ? "publicmode" : "";
		echo $this->loggedin===true ? "loggedin" : "notloggedin";
		echo \F3::get('initial_open')==1 ? "initial_open" : "";
		echo \F3::get('auto_mark_as_read')==1 ? "auto_mark_as_read" : "";
	?>">

	<div id="toolbar" class="navbar navbar-fixed-top navbar-inverse"><div class="navbar-inner"><div class="container">
		<form class="navbar-search"><input type="text" class="search-query" placeholder="Search"></form>
		<ul class="nav"><li class="divider-vertical"></li></ul>

		<button class="btn btn-small pull-left" data-action="all-read">mark all as read</button>

		<div class="pull-left">
			<button class="btn btn-small pull-left" data-action="refresh"><i class="icon-repeat"></i></button>
			<button class="btn btn-small" data-action="prev"><i class="icon-chevron-up"></i></button>
			<button class="btn btn-small" data-action="next"><i class="icon-chevron-down"></i></button>
		</div>

		<div class="pull-right">
			<button class="btn btn-small active" data-action="view-expanded"><i class="icon-th-list"></i></button>
			<button class="btn btn-small" data-action="view-collapsed"><i class="icon-list"></i></button>
			<?php
				if ($this->loggedin === true) {
					echo '<button class="btn btn-small"><i class="icon-cog"></i></button>';
					if (\F3::get('auth')->enabled() === true) echo '<button class="btn btn-small">logout</button>';
				}
				else echo '<button class="btn btn-small"login</button>';
			?>
		</div>
	</div></div></div>


	<div id="sidebar">
		<?PHP $active = (\F3::get('homepage')) ? \F3::get('homepage') : 'unread' ?>
		<ul class="nav nav-list sidebar-list-stats">
			<li class="nav-header">RSS</li>
			<li class="nav-btn nav-type nav-unread" data-nav-type="type" data-action="unread">
				<a href="#" class="row-fluid">
					<span class="span9">unread</span>
					<span class="span3 stats-unread"></span>
				</a>
			</li>
			<li class="nav-btn nav-type nav-starred" data-nav-type="type" data-action="starred">
				<a href="#" class="row-fluid">
					<span class="span9">starred</span>
					<span class="span3 stats-starred"><span class="no-badge"></span></span>
				</a>
			</li>
			<li class="nav-btn nav-type nav-all" data-nav-type="type" data-action="all">
				<a href="#" class="row-fluid">
					<span class="span9">all</span>
					<span class="span3 stats-all"><span class="no-badge"></span></span>
				</a>
			</li>
		</ul>
		<hr>

		<div class="sidebar-wrapper">
			<ul class="nav nav-list sidebar-list-tags"><li class="nav-header">Tags</li></ul>
			<hr>
			<ul class="nav nav-list sidebar-list-sources"><li class="nav-header">Sources</li></ul>
		</div>
	</div>

	<div id="content"></div>

	<script>var App = App || {}; App.rootPath = "<?PHP echo $this->base; ?>"</script>
	<script src="js/jquery.min.js"></script>
	<script src="js/widgets.js"></script>
	<script src="js/app.js"></script>
	<script src="js/modules.js"></script>
</body>
</html>