<?PHP
	$title = $this->item['title'];
	$content = str_replace('&#34;', '"', $this->item['content']);
	$sourcetitle = $this->item['sourcetitle'];
	$this->viewHelper = new \helpers\ViewHelper();
	if (isset($this->search)) {
		$sourcetitle = $this->viewHelper->highlight($sourcetitle, $this->search);
		$title = $this->viewHelper->highlight($title, $this->search);
		$content = $this->viewHelper->highlight($content, $this->search);
	}
	$title = $this->viewHelper->lazyimg($title);
	$content = $this->viewHelper->lazyimg($content);
	$date = $this->viewHelper->dateago($this->item['datetime']);
?>
<div id="entry<?PHP echo $this->item['id']; ?>" class="modal entry <?PHP echo $this->item['unread']==1 ? 'unread' : ''; ?>">
	<div class="modal-header">
		<a href="<?PHP echo $this->item['link']; ?>" class="entry-icon">
			<?PHP if(strlen(trim($this->item['icon']))>0 && $this->item['icon']!="0") : ?>
			<img src="<?PHP echo 'favicons/'.$this->item['icon']; ?>" alt="<?PHP echo $sourcetitle ?>" />
			<?PHP endif; ?>
		</a>
		<span class="entry-time">&bullet; <?PHP echo $date; ?></span>
		<a href="<?PHP echo $this->item['link']; ?>" class="entry-source entry-source<?PHP echo $this->item['source']; ?>" target="_blank"><?PHP echo $sourcetitle ?></a>
		<div class="entry-tags">
			<?PHP foreach($this->item['tags'] as $tag => $color) : ?>
				<div class="label entry-tags-tag" style="background-color:<?PHP echo $color; ?>"><?PHP echo $tag; ?></div>
			<?PHP endforeach; ?>
		</div>


		<h3><?PHP echo $title; ?></h3>

		<?PHP if(isset($this->item['thumbnail']) && strlen(trim($this->item['thumbnail']))>0) : ?>
			<div class="entry-thumbnail">
				<a href="<?PHP echo $this->item['link']; ?>"><img src="<?PHP echo 'thumbnails/'.$this->item['thumbnail']; ?>" alt="<?PHP echo $this->item['title']; ?>" /></a>
			</div>
		<?PHP endif; ?>
	</div>
	<div class="modal-body entry-content<?PHP if (strlen(strip_tags($content))<500) echo ' entry-content-short'; ?>">
		<?php echo $content; ?>
	</div>
	<div class="modal-footer">
		<button class="btn btn-mini entry-newwindow pull-right"><i class="icon-share-alt"></i>open</button>
		<div class="btn-group pull-left">
			<button class="btn btn-mini entry-starr"><?php
				echo ($this->item['starred'] === 1 ? '<i class="icon-star"></i> unstar' :
					'<i class="icon-star-empty"></i> star');
			?></button>
			<button class="btn btn-mini entry-unread"><?php
				echo ($this->item['unread'] === 1 ? '<i class="icon-ok-circle"></i> mark as read' :
					'<i class="icon-ok-circle"></i> mark as unread');
			?></button>
			<!-- <button class="btn entry-loadimages">load images</button> -->
		</div>
		<div class="btn-group pull-left">
			<button class="btn btn-mini entry-sharereadabibuttonty"><i class="icon-bookmark"></i> readability</button>
			<button class="btn btn-mini entry-shareemail"><i class="icon-envelope"></i> email</button>
		</div>
	</div>
</div>
